# core/contracts.py
from typing import Protocol, Dict, Any

Json = Dict[str, Any]

class Provider(Protocol):
    name: str
    def supports(self, capability: str) -> bool: ...
    def submit(self, payload: Json) -> str: ...
    def status(self, job_id: str) -> Json: ...
    def fetch_result(self, job_id: str) -> Json: ...

class HostAdapter(Protocol):
    def log(self, level: str, msg: str) -> None: ...
    def set_status(self, text: str) -> None: ...
    # asset import stays host-specific; adapter will implement when you expand
